<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;

// Unversioned auth route
Route::middleware('auth:sanctum')->group(function () {
    Route::get('/user', function (Request $request) {
        return response()->json($request->user(), 200);
    });
});

// Versioned API routes
Route::prefix('v1')->middleware('auth:sanctum')->group(function () {
    // This would be auto-generated by our make:api command
});

Route::prefix('auth')->group(function() {
    // Public routes
    Route::post('/register', [AuthController::class, 'register'])->name('register');
    Route::post('/login', [AuthController::class, 'login'])->name('login');
    
    // Protected routes
    Route::middleware('auth:sanctum')->group(function() {
        Route::post('/logout', [AuthController::class, 'logout']);
        // Other protected API routes
    });
});
